default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: admin123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: demo_project_development

test:
  <<: *default
  database: demo_project_test

production:
  <<: *default
  database: demo_project_production
  username: demo_project
  password: <%= ENV['DEMO_PROJECT_DATABASE_PASSWORD'] %>
